version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: escuela_musica
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
    depends_on:
      - db
